version: '3'

volumes:
  local_postgres_data: {}

services:
  web:
    build:
      context: .
    environment:
      - DJANGO_SETTINGS_MODULE=example.settings
    depends_on:
      - db
    volumes:
      - ./airports:/app/airports:delegated,rw
      - .:/app:cached
    ports:
      - "8000:8000"
    command: sh -c "python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgis/postgis:latest
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
