version: '3'

services:
  web:
    container_name: "web"
    build:
      context: .
    environment:
      - DJANGO_SETTINGS_MODULE=localsite.settings
    volumes:
      - ./airports:/app/airports:delegated,rw
      - .:/app:cached
    ports:
      - "8000:8000"
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
