# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
cache: pip
sudo: false

python:
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  apt:
    sources:
      - sourceline: ppa:ubuntugis/ppa
    packages:
      - gdal-bin
      - libgdal-dev
      - libproj-dev
      - spatialite-bin
      - python3-dev
      - libsqlite3-mod-spatialite

install:
  # install python gdal package (version must match installed GDAL lib)
  - CFLAGS=-I/usr/include/gdal pip install GDAL==$(gdal-config --version | cut -d. -f1-2).*

  # other dependencies
  - pip install tox-travis

script:
  - tox
