# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO=2.0

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y spatialite-bin binutils libproj-dev gdal-bin

install:
  - pip install tox-travis
  - pip install -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: tox

after_success:
  - codecov -e DJANGO
