# Generated by Django 2.0.3 on 2018-03-16 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='iata',
            field=models.CharField(blank=True, db_index=True, max_length=3, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='IATA/FAA code'),
        ),
    ]
