# Generated by Django 2.0.3 on 2018-03-22 00:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0002_auto_20180316_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ['iata']},
        ),
        migrations.RemoveField(
            model_name='airport',
            name='airport_id',
        ),
        migrations.AlterField(
            model_name='airport',
            name='iata',
            field=models.CharField(blank=True, db_index=True, max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='IATA/FAA code'),
        ),
    ]
