# Generated by Django 3.2.10 on 2021-12-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airports", "0003_auto_20190321_1026"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airport",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
