# Generated by Django 3.2.10 on 2021-12-22 08:12

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0004_alter_airport_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name="airport",
            old_name="city_name",
            new_name="municipality",
        ),
        migrations.RenameField(
            model_name="airport",
            old_name="local",
            new_name="local_code",
        ),
    ]
